app/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^', include('grade.urls')),
    url(r'^admin/', admin.site.urls),
]

grade/urls.py
from django.conf.urls import url

from . import views

app_name = 'grade'
urlpatterns = [
    url(r'^$', views.login, name='login'),
    url(r'^signup$', views.signup, name='signup'),
    url(r'keepuser&', views.keepUser, name='keepuser'),
    url(r'^index$', views.index, name='index'),
    url(r'^detail$', views.operand, name='operand' ),
    url(r'^show$', views.show, name='show' ),
    url(r'^about$', views.about, name='about' ),
]

grade/models.py
from django.db import models

class Grade(models.Model):
    subject = models.CharField(max_length=200)
    score = models.FloatField(default=0)
    full = models.FloatField(default=0)
    total = models.FloatField(default=0)
    grade = models.CharField(max_length=200)
    credit = models.FloatField(default=0)
    mean = models.FloatField(default=0)
    sd = models.FloatField(default=0)
    final_score = models.FloatField(default=0)
    final_full = models.FloatField(default=0)
    def __str__(self):
        return self.subject

grade/views.py
from django.http import HttpResponse
from django.shortcuts import render
from django.utils import timezone
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from .models import Grade
import math
import csv

def login(request):
    return render(request,"grade/login.html")

def signup(request):
    return render(request,"grade/signup.html")

def keepUser(request):
    name = request.POST['name']
    password = request.POST['password']    

    if name == '' or len(password) == 0:
        return render(request, 'grade/error_register.html')

    user = User.objects.create_user(username=name, password=password)
    user.save()
    return render(request, 'grade/success.html', {'name':name})

def index(request):
    user = User.objects.all()
    name = request.POST['name']
    password = request.POST['password']
    user = authenticate(username=name, password=password)
    if user is not None:
        # A backend authenticated the credentials
        login(request)
        return render(request,"grade/index.html")
    else:
        # No backend authenticated the credentials
        return render(request, 'grade/error_login.html')  

def about(request):
    return render(request,"grade/about.html")

def operand(request):
    error_message = 0
    subject = ""
    score = 0
    full = 1
    credit = 1
    mean = 0
    sd = 0
    final_score = 0
    final_full = 1
    try:
        subject = request.POST['subject']
        score = float(request.POST['score'])
        full = float(request.POST['full'])
        credit = float(request.POST['credit'])
        mean = float(request.POST['mean'])
        sd = float(request.POST['sd'])
        final_score = float(request.POST['final_score'])
        final_full = float(request.POST['final_full'])
    except:
        error_message = 1
        
    if(subject != ""):
        equation = (float(score)+float(final_score))*100/(float(full)+float(final_full))  # make score to 100 percent
        net = ("%.2f" % round(equation,2))  # make decimal two position
        if float(net) < 0.0:
            grade = 'Null'
        elif float(net) < float(mean)-(1.5*float(sd)):
            grade = 'F'
        elif float(net) < float(mean)-float(sd):
            grade = 'D'
        elif float(net) < float(mean)-(0.5*float(sd)):
            grade = 'D+'
        elif float(net) < float(mean):
            grade = 'C'
        elif float(net) < float(mean)+(0.5*float(sd)):
            grade = 'C+'
        elif float(net) < float(mean)+(1*float(sd)):
            grade = 'B'
        elif float(net) < float(mean)+(1.5*float(sd)):
            grade = 'B+'
        elif float(net) >= float(mean)+(1.5*float(sd)):
            grade = 'A'
        elif float(net) > 100.0:
            grade = 'Null'
                
        information = Grade(subject=subject, score=score, full=full, total=net, grade=grade, credit=credit, mean=mean, sd=sd, final_score=final_score, final_full=final_full)
        information.save()
    # user hits the Back button.
    return render(request,"grade/detail.html")

def show(request):
    subject_list = Grade.objects.all()
    keep_grade = ['A','B+','B','C+','C','D+','D','F']
    grade_keep = [4,3.5,3,2.5,2,1.5,1,0]
    grade_alp = []
    cal_credit = []
    tmp = 0
    sum_credit = 0
    # this loop will pull data from database that calculate grade of that semeter
    for i in range(len(subject_list)):
        grade_alp.append(str(subject_list[i].grade))
        cal_credit.append(float(subject_list[i].credit))
        sum_credit += float(subject_list[i].credit)
        for j in range(0,len(keep_grade)):
            if(str(subject_list[i].grade) == keep_grade[j]):
                tmp += (subject_list[i].credit*grade_keep[j])
                
    gpa = 0
    # calculate GPA
    if sum_credit != 0:
        gpa = tmp/sum_credit
        result = math.floor(gpa * 100) / 100
        
    print(grade_alp)
    print(cal_credit)
    print(tmp)
    print(sum_credit)
    # Calculate balance of paylist.
    return render(request,"grade/show.html",{'subject_list':subject_list, 'result':result})

grade/templates/grade/about.html
<!DOCTYPE html>
<html>
<head><link href="/static/bootstrap/css/bootstrap.min.css" rel="stylesheet">
<style type="text/css">
div.absolute {
    position: absolute;
    left: 600px;
    width: 850px;
    height: 120px;
}
   body { background: pink !important; } /* Adding !important forces the browser to overwrite the default style applied by Bootstrap */
</style>
</head>
<title>About</title>
<body bgcolor = pink>
<center>
<h2 style = "text-align: center;color:rgb(0, 0, 0);">เกี่ยวกับเรา</h2>
{% load static %}
<img src="{% static "grade/a.jpg" %}" alt="Grade"/><br><br>
<div class="card">
  <h3 class="card-header">โปรแกรมจำลองเกรด</h3>
<p><div class="card-block">
    <dd><h4 class="card-title">โปรแกรมของเราคือโปรแกรมที่ช่วยให้คุณสามารถคาดการณ์เกรดล่วงหน้า ว่าจะได้เกรดอะไร ตามการคาดการณ์คะแนนของคุณเอง</h4></p><br>
</center>
<center>
<font size="4">
    <p class="card-text">คุณสมบัติ<br>
<div class="absolute" align="left">
<ui>
<li> สามารถกรอกคะแนนกลางภาคที่คุณได้ และคะแนนไฟนอลที่คุณคาดการณ์ เพื่อทำการคำนวณ</li>
<li> สามารถใส่ค่าเฉลี่ย และส่วนเบี่ยงเบนมาตรฐานเพื่อเพิ่มความแม่นยำในเกรดของคุณที่จะได้มา</li>
<li> สามารถให้ทุกวิชาที่คุณเรียนในเทอมนั้นๆ เพื่อแสดงเกรดเฉลี่ยออกมาให้คุณอีกด้วย</li>
<li> รูปแบบการแสดงผลเป็นตาราง เหมือนใบผลการเรียน</li></ui>
</font>
</p>

</div><br><br><br><br><br><br><br>
   <center> <a href="{% url 'grade:operand' %}" class="btn btn-primary">เข้าสู่โปรแกรม</a>
  

</div>
</center>
</body>
</html>

grade/templates/grade/base.html
<html>
<head>
    <link href="/static/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <title>Grade Simulator</title>
    <style type="text/css">
        body { background: pink !important; } /* Adding !important forces the browser to overwrite the default style applied by Bootstrap */
    </style>
</head>
<body>
    <center>
    <h1>{% block header_text %}{% endblock %}</h1>
    <form action="{% block form_action %}{% endblock %}" method="post">
        {% csrf_token %}
        <p>Name:</p><br>
        <input type="text" name="name"><br>
        <p>Password:</p><br>
        <input type="password" name="password" ><br><br>
        <input type="submit" class="btn btn-primary" >
    </form>  

    {% block link %}   
    {% endblock %}

    </center>

</body>
</html>

grade/templates/grade/detail.html
<!DOCTYPE html>
<html>
<head><link href="/static/bootstrap/css/bootstrap.min.css" rel="stylesheet">
<style type="text/css">
   body { background: pink !important; } /* Adding !important forces the browser to overwrite the default style applied by Bootstrap */
</style>
</head>
<center>
<body bgcolor="#00BFFF" >
<h2 style = "text-align: center;color:rgb(0, 0, 255);">โปรแกรมจำลองเกรด</h2>
<form action="{% url 'grade:operand'%}" method="post">
{% csrf_token %}

    วิชา:
    <input id='1' type="text" name="subject" required><br><br>
    หน่วยกิต:
    <input id='2' type="number" name="credit" step="any" min="0"><br><br>
   คะแนนกลางภาค:
    <input id='3' type="number" name="score" step="any" min="0"><br><br>
    คะแนนเต็ม:
    <input id='4' type="number" name="full" step="any" min="0"><br><br>
    คะแนนปลายภาค:
    <input id='5' type="number" name="final_score" step="any" min="0"><br><br>
    คะแนนเต็ม:
    <input id='6' type="number" name="final_full" step="any" min="0"><br><br>
    ค่าเฉลี่ย:
    <input id='7' type="number" name="mean" step="any" min="0"><br><br>
    ส่วนเบี่ยงเบนมาตรฐาน:
    <input id='8' type="number" name="sd" step="any" min="0"><br><br>

    <input id='9' class="btn btn-primary" type="submit">

</form>
<br><a id='10' href = "{% url 'grade:show' %}">ดูผลการเรียน</a>
<br><a href = "{% url 'grade:index' %}">กลับสู่หน้าหลัก</a>
</form>
</body>
</center>
</html>

grade/templates/grade/error_login.html
<html>
<head>
    <link href="/static/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <title>Grade Simulator</title>
    <style type="text/css">
        body { background: pink !important; } /* Adding !important forces the browser to overwrite the default style applied by Bootstrap */
    </style>
</head>
<body>
    <center>
    <h1>Username or Password is wrong. Please try again!</h1>
    <a href="{% url 'grade:login' %}" class="btn btn-primary" name="backtologin">back to login</a>
    </center>
</body>
</html>

grade/templates/grade/error_register.html
<html>
<head>
    <link href="/static/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <title>Grade Simulator</title>
    <style type="text/css">
        body { background: pink !important; } /* Adding !important forces the browser to overwrite the default style applied by Bootstrap */
    </style>
</head>
<body>
    <center>
    <h1>Something wrong. Please try again!</h1>
    <a href="{% url 'grade:signup' %}" class="btn btn-primary" name="signup">sign up</a>
    </center>
</body>
</html>

grade/templates/grade/index.html
<!DOCTYPE html>
<html>
<head><link href="/static/bootstrap/css/bootstrap.min.css" rel="stylesheet">
<style type="text/css">
   body { background: pink !important; } /* Adding !important forces the browser to overwrite the default style applied by Bootstrap */
</style>
</head>
<title>Grade Simulator</title>
<body bgcolor = pink>
<center>
<h2 style = "text-align: center;color:rgb(0, 0, 0);">โปรแกรมจำลองเกรด</h2>
{% load static %}
<img src="{% static "grade/a.jpg" %}" alt="Grade"/><br><br>
<div class="alert alert-danger" role="alert">
  <strong>1.</strong>
  <a href="{% url 'grade:operand' %}" class="alert-link" name="enter_program">คลิ้กที่นี่</a>
  เพื่อเข้าสู่โปรแกรม
</div>
<div class="alert alert-danger" role="alert">
  <strong>2.</strong>
  <a href="{% url 'grade:about' %}" class="alert-link" name="about">คลิ้กที่นี่</a>
  เพื่อดูเกี่ยวกับเรา
</div>
</center>
</body>
</html>

grade/templates/grade/login.html
{% extends 'grade/base.html' %}
{% block header_text %}Log in{% endblock %}
{% block form_action %}{% url 'grade:index' %}{% endblock %}
{% block link %}<a href="{% url 'grade:signup' %}" class="btn btn-primary" name="signup">sign up</a>{% endblock %}

grade/templates/grade/show.html
<html>
<head><link href="/static/bootstrap/css/bootstrap.min.css" rel="stylesheet">
<style type="text/css">
   body { background: pink !important; } /* Adding !important forces the browser to overwrite the default style applied by Bootstrap */
</style>
</head>
<center>
<body bgcolor= pink>
<h2 style = "text-align: center;color:rgb(0, 0, 255);">โปรแกรมคำนวณเกรด</h2>
<table border=1 style="width:50%">
        <tr>
            <th>วิชา</th>
	    <th>คะแนนที่ได้</th>
            <th>เกรดที่ได้</th>
        </tr>
{% for data in subject_list %}
<tr>
            <td>{{ data.subject}}</td>
		<td>{{ data.total }}</td>
                <td>{{data.grade}}</td>
        </tr>
{% endfor %}
<tr>
            <td style="text-align: center;" colspan="3">เกรดเฉลี่ยรวม  {{ result }}</td>
        </tr>
</table>
<br><a href = "{% url 'grade:operand' %}">เข้าสู่โปรแกรม</a>
<br><a href = "{% url 'grade:index' %}">กลับสู่หน้าหลัก</a>
</body>
</center>
</html>

grade/templates/grade/signin.html
{% extends 'grade/base.html' %}
{% block header_text %}Sign up{% endblock %}
{% block form_action %}{% url 'grade:keepuser' %}{% endblock %}
{% block link %}<a href="{% url 'grade:login' %}" class="btn btn-primary">back to login</a>{% endblock %}

grade/templates/grade/signup.html
{% extends 'grade/base.html' %}
{% block header_text %}Sign up{% endblock %}
{% block form_action %}{% url 'grade:keepuser' %}{% endblock %}
{% block link %}<a href="{% url 'grade:login' %}" class="btn btn-primary">back to login</a>{% endblock %}

grade/templates/grade/success.html
<html>
<head>
    <link href="/static/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <title>Grade Simulator</title>
    <style type="text/css">
        body { background: pink !important; } /* Adding !important forces the browser to overwrite the default style applied by Bootstrap */
    </style>
</head>
<body>
    <center>
    <h1>Success</h1>
    <p>Thank : {{ name }}</p>
    <a href="{% url 'grade:login' %}" class="btn btn-primary" name="backtologin">back to login</a>
    </center>
</body>
</html>